### ISSUE TITLE
M2.4.4 and laminas/laminas-crypt depency

### ISSUE THREAD

**Issue by Nuranto** [mageplaza/magento-2-smtp#371]
Since Magento remove dependency from laminas/laminas-crypt, and since it is not a dependency of laminas/laminas-email (only a suggest), I think you should add `laminas/laminas-crypt` as a requirement in composer

See : https://github.com/magento/magento2/pull/33211/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

And : https://github.com/laminas/laminas-mail/blob/2.17.x/composer.json

Error it may cause : 

```
[2022-05-24T10:24:03.148203+00:00] .CRITICAL: Error: Class "Laminas\Crypt\Hmac" not found in /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Smtp/Auth/Crammd5.php:130
Stack trace:
#0 /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Smtp/Auth/Crammd5.php(70): Laminas\Mail\Protocol\Smtp\Auth\Crammd5->hmacMd5('XyHI2nAT4qpRNtK...', '<96345343165338...')
#1 /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Smtp.php(291): Laminas\Mail\Protocol\Smtp\Auth\Crammd5->auth()
#2 /var/www/html/vendor/laminas/laminas-mail/src/Transport/Smtp.php(396): Laminas\Mail\Protocol\Smtp->helo('localhost')
#3 /var/www/html/vendor/laminas/laminas-mail/src/Transport/Smtp.php(378): Laminas\Mail\Transport\Smtp->connect()
#4 /var/www/html/vendor/laminas/laminas-mail/src/Transport/Smtp.php(389): Laminas\Mail\Transport\Smtp->lazyLoadConnection()
#5 /var/www/html/vendor/laminas/laminas-mail/src/Transport/Smtp.php(246): Laminas\Mail\Transport\Smtp->connect()
#6 /var/www/html/vendor/mageplaza/module-smtp/Mail/Transport.php(126): Laminas\Mail\Transport\Smtp->send(Object(Laminas\Mail\Message))
```

**Comment by ioweb-gr** [comment]
I'm facing the same issue on 2.4.5-p1 with this module
